name: 'release drafter'

inputs:
  repo-token:
    description: 'My github token'
    require: false
    default: ''
outputs:
  label-name:
    description: 'label name'

runs:
  using: 'node16'
  main: '../../../dist/release/index.js'
