name: Set Label

on:
  pull_request:
    types: [opened]
    branches:
      - master
jobs:
  apply-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check out repo content
        uses: actions/checkout@v3
      - name: script build
        run: ncc build .github/actions-scripts/labeler.mjs -o dist
      - name: Run script
        uses: ./.github/actions/labeler
        id: labels-script
        with:
          pr-number: ${{ github.event.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: label list
        run: |
          echo "${{ steps.labels-script.outputs.label-list }}"
