name: Set Label
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    types: [opened]
    branches:
      - master
jobs:
  apply-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check out repo content
        uses: actions/checkout@v3
      - name: Run script
        uses: Khyosunny/labeler@v1
        id: labels-script
        with:
          pr-number: ${{ github.event.number }}
      - name: label list
        run: |
          echo "${{ steps.labels-script.outputs.label-list }}"
