name: Deploy production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Vercel 배포'

    steps:
      - name: Install Vercel CLI Client
        uses: actions/checkout@v3
        run: npm install --global vercel@latest
        with:
          path: packages/client
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_TEST }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      - name: echo
        run: |
          echo ${{ github.path }} ${GITHUB_WORKSPACE}
