name: Deploy production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'Vercel 배포'

    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI

      - uses: actions/checkout@v3
      - name: Install Vercel CLI Client
      - with:
          path: packages/client
        run: npm install --global vercel@latest
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_TEST }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      - name: echo
        run: |
          echo ${{ secrets.VERCEL_PROJECT_ID_TEST }} ${{ github.path }}
          echo "{path}" >> $GITHUB_PATH
          echo ${GITHUB_WORKSPACE}
