name: Deploy production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: call deploy
      #   uses: ./.github/workflows/call-workflow.yml
      #   with:
      #     config-path: ${{ github.event.release }}

      - name: echo release
        run: |
          echo "${{ toJSON(github.event.release) }}"
