name: deploy

on:
  workflow_dispatch:
    inputs:
      region:
        required: true
        type: string
      env:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Echo variables
        run: |
          echo "env: ${{ github.event.inputs.env }}"
          echo "region: ${{ github.event.inputs.region }}"
