name: Deploy production

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 'test production client'
    steps:
      - name: 'checkout@v3'
        uses: actions/checkout@v3
      - name: 'actions'
        id: foo
        uses: ./.github/actions/test
        with:
          status: 'client'
        # - name: Install Vercel CLI
        #   run: npm install --global vercel@latest
        # - name: Deploy Project Artifacts to Vercel
        #   run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
        #   env:
        #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_TEST }}
        #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          echo '${{ toJSON(github) }}'
          echo '${{ github.event.release.body }}'
          echo '${{ contains(github.event.release.body, '#[0-9]+') }}'
          echo '${{ github.action_path }}'
          echo '${{ steps.foo.outputs.pathVariable }}'
        shell: bash
