name: Release Drafter

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths:
      - packages/common/**
      - packages/client/**

jobs:
  update_release_draft:
    # if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
      - run: |
          echo ${{ github.head_ref }} ${{ github.event.action }} PR #${{ github.event.number }} has been merged
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
