name: Release Drafter

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths:
      - packages/common/**
      - packages/global/**

jobs:
  update_release_draft:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
      - run: echo "${{ github.event.action }}"
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
