name: Release Drafter

on:
  push:
    branches:
      - master
    paths:
      - packages/common/**
      - packages/client/**

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ github.action_path }} .... ${{ github.action_ref }}
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
