name: Release Drafter

on:
  push:
    branches:
      - master
    paths:
      - packages/common/**
      - packages/client/**

jobs:
  update_release_draft:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo ${{ github.head_ref }} github.event.pull_request.merged
